hhvm/hhast

src/__Private/LinterCLIConfig.php
Hi there,
It looks like there might be a typo wrt the linter blacklist. I have a `hh-lint.json` like
```
...
"builtinLinters": "none",
"namespaceAliases": { "HHAST": "Facebook\\HHAST\\Linters" },
"extraLinters": [
"HHAST\\CamelCasedMethodsUnderscoredFunctionsLinter",
"HHAST\\MustUseBracesForControlFlowLinter"
]
...
```
and no linters were run against the target files :/
Changing this line fixed things for me!
=> fix blacklisted linter normalization typo

src/find_offset_of_leading.php
I've been working on a linter that disallows invocations of particular functions by name, and was testing it out on a ~5500 line source file. `getDescendantsWhere` consumes a very large amount of time (on the order of the number of lint errors and AST size).
I _think_ removing it would be okay as the `findWithParents` seems like enforces the same or a similar invariant. If not, maybe there's a cleaner way to enforce this? (i.e. not traversing from `$root` with every recursive call?)
Here's some XHPROF's from before and after!
In general, are you open to changes/alternative approaches in `find_offset_of_leading`?
=> remove slow invariant

src/find_offset_of_leading.php
Just looking for feedback here -- this is what I was envisioning for a follow up to #16. I'm assuming that an AST isn't able to be mutated while recursively calling `find_offset_of_leading` but ¯\\\_(ツ)\_/¯. I'm happy to write tests but frankly I don't know where to start or what to use as an example.
Thanks for indulging me here
Oh and here's some more XHPROFs for this one:
=> re-use stack while recursively calling find_offset_of_leading

src/__Private/codegen/schema.php
When I attempt to run `bin/update-codegen` on a fresh clone from master, I get the following:
```
[22] $> bin/update-codegen
#!/usr/bin/env hhvm
Fatal error: Uncaught exception 'Facebook\TypeAssert\IncorrectTypeException' with message 'Expected type 'no extra shape fields', got type 'string'
Type trace:
#0 shape[description]
' in /Users/bradleydavis/github/hhast_upstream/vendor/hhvm/type-assert/src/IncorrectTypeException.php:41
Stack trace:
#0 /Users/bradleydavis/github/hhast_upstream/vendor/hhvm/type-assert/src/IncorrectTypeException.php(53): Facebook\TypeAssert\IncorrectTypeException::withType()
#1 /Users/bradleydavis/github/hhast_upstream/vendor/hhvm/type-assert/src/TypeSpec/__Private/ShapeSpec.php(94): Facebook\TypeAssert\IncorrectTypeException::withValue()
#2 …
```
=> add additional fields to TSchema shape def

src/find_offset.php
Something I've run into:
Suppose you really, really dislike comments and so you write this:
```
class AllCodeIsSelfDocumentingLinter
extends ASTLinter<SingleLineComment> {
<<__Override>>
protected static function getTargetType(): classname<SingleLineComment> {
return SingleLineComment::class;
}
<<__Override>>
public function getLintErrorForNode(
SingleLineComment $node,
vec<EditableNode> $parents,
): ?ASTLintError<SingleLineComment> {
return new ASTLintError(
$this,
'bah humbug',
$node,
);
}
}
```
whenever this error is triggered, you get an `IncorrectTypeException`:
```
Warning: Destructor threw an object exception: exception 'HH\InvariantException' with message 'counter Facebook\HHAST\Linters\AllCodeIsSelfDocumentingLinter#processErrors destroyed without calling ::end()' in …
```
=> make find_offset_of_leading work for trivia

src/__Private/LinterCLI.php
Overriding shouldLintFile a la
```
<<__Override>>
public static function shouldLintFile(string $file): bool {
return false;
}
```
doesn't appear to do anything (still runs the linter).
=> make use of shouldLintFile

src/Linters/suppress_ast_linter_error.php, tests/fixtures/SuppressASTLinterAwait/await_in_while.php.in
…when looking if we should suppress a linting error.
The simple example where having ReturnStatement in that list becomes troublesome:
```
...
return some_banned_function($param);
```
Since the error node is the function we immediately hit the ReturnStatement before the comment and stop. Alternatively I assume the comment could be inbetween return and the function, but that seems harder to read.
=> Suppress Linter error: Remove ReturnStatement from the list of statements to stop at

src/__Private/LinterCLI.php
Hopefully this logic is correct:
- Running 'bin/hhast-lint' works as before
- If the user specifies a directory, check if the directory directly contains a hhast-lint.json. If so, print warning message, but still lint everything in the specified directory.
- If the user specifies a file, just lint the file.
- If the user specifies multiple PATH arguments, print warning message for each case it applies
=> Warn if path contains a hhast-lint.json

src/Linters/BaseASTLinter.php, src/Linters/LinterException.php, src/__Private/LintRun.php, src/__Private/LinterCLI.php
Depends on (and includes) #76 - only the last two commits in this PR need reviewing
Example output:
```
A linter threw an exception:
Linter: Facebook\HHAST\Linters\AsyncFunctionAndMethodLinter
File: /Users/fred/code/definition-finder/tests/data/php_class_contents.php:13:3
>
> class Foo {
>   function defaultVisibility() {}
^ HERE
Exception: Facebook\TypeAssert\IncorrectTypeException
Message: Expected type 'Facebook\HHAST\EditableList', got type 'Facebook\HHAST\Missing'
Trace:
#0 /Users/fred/code/hhast/vendor/hhvm/type-assert/src/IncorrectTypeException.php(54): Facebook\TypeAssert\IncorrectTypeException::withType()
#1 /Users/fred/code/hhast/vendor/hhvm/type-assert/src/TypeSpec/__Private/InstanceOfSpec.php(29): Facebook\TypeAssert\IncorrectTypeException::withValue()
#2 …
```
=> Nice handling of linters throwing exceptions

src/Linters/FunctionNamingLinter.php, tests/AsyncFunctionAndMethodLinterTest.php
for example, `class Foo { function bar() {} }` is valid PHP.
=> Fix running function naming linters against PHP methods without modifiers

composer.lock, src/Migrations/AssertToExpectMigration.php, src/__Private/MigrationCLI.php, tests/MigrationsTest.php, tests/fixtures/migrations/change_assert_to_expect.php.expect, tests/fixtures/migrations/change_assert_to_expect.php.in
- Migrates assert calls to their respective expect function (let me know if I missed any others that directly translate)
- Adds 'use function Facebook\FBExpect\expect' according to #91 
- Doesn't handle all of the cases with comments correctly...working on it
Will add examples of each case listed in #91 , or perhaps refactor how MigrationsTest works (currently can only test one .in and .expect file)
=> Assert to Expect migration

.hhconfig, src/Migrations/AssertToExpectMigration.php
Don't need two booleans to determine whether we need to add `use function Facebook\FBExpect\expect;` 
`useExpectFunctionNeeded` starts out false and is only set to true if there are expect calls. It is set to false if the use statement already exists or if the migration adds it.
=> Use only one bool

src/Linters/FixableASTLintError.php, src/__Private/Diff/Diff.php, src/__Private/Diff/DiffOp.php, src/__Private/Diff/StringDiff.php, src/__Private/LintRunCLIEventHandler.php
This PR depends on (and includes) the LSP as-you-type changes
This is pretty slow if running it with the jit on with just a few files, mostly due to having to flatten the AST to a file, bu tfine with the jit off, or when running across a few files.
I'm hoping to use this to:
- implement LSP support for all fixable lint errors (i.e. file changes => document textEdit structs)
- drastically simplify the linter/lint error class hierarchy - if we have `getFixedFile`, we can render a diff.
=> Add real diff implementation (Myers algorithm), use it to display previews

composer.lock, src/__Private/LSPImpl/Client.php, src/__Private/LSPImpl/DidChangeWatchedFilesNotification.php, src/__Private/LSPImpl/DidCloseTextDocumentNotification.php, src/__Private/LSPImpl/ExecuteCommandCommand.php, src/__Private/LSPImpl/InitializedNotification.php, src/__Private/LSPLib/Client.php, src/__Private/LSPLib/Server.php, src/__Private/LintRun.php, src/__Private/LintRunCLIEventHandler.php, src/__Private/LintRunEventHandler.php, src/__Private/LintRunJSONEventHandler.php, src/__Private/LintRunLSPPublishDiagnosticsEventHandler.php
fixes #130
`write()` might only write part of the data (it returns number of bytes written). `writeAsync()` (new) does the whole lot, but can interleave.
1. Convert all the client => server methods to async
2. Use writeAsync
3. Build a queue so that we don't get a chunk from one message
interleaved with a chunk from another
=> Make LSP message flushing async, complete, and chunk in-order

docs/linters-usage.md
In the linters usage doc, the link to `TConfigFile` needs updated, as the containing class has been renamed.
=> Fix TConfigFile link

src/Migrations/PHPLessThanGreaterThanOperatorMigration.php, src/__Private/MigrationCLI.php, tests/MigrationsTest.php, tests/fixtures/migrations/ltgt.php.expect, tests/fixtures/migrations/ltgt.php.in
There's already a PHP inequality /linter/ but that's more ambitious:
that converts to `!==`.
The migration does the safe change.
=> Add <> to != migration

src/Linters/PreferLambdasLinter.php, tests/PreferLambdasLinterTest.php, tests/fixtures/PreferLambdasLinter/prefer_lambdas.php.autofix.expect, tests/fixtures/PreferLambdasLinter/prefer_lambdas.php.expect, tests/fixtures/PreferLambdasLinter/prefer_lambdas.php.in
This change adds an autofixing linter that converts [PHP anonymous functions](http://php.net/manual/en/functions.anonymous.php) to [Hack lambdas](https://docs.hhvm.com/hack/lambdas/introduction). It does not fix anonymous functions that use variables by reference which have no equivalent lambda.
In my implementation of `getFixedNode` I am not sure if there is a better approach to copying the child nodes from the anonymous function to the lambda expression. I use `?? Missing()` extensively; any suggestions for a better approach are very welcome.
A future improvement which I did not implement here would be to examine the body of the anonymous function and, if it returns the result of a single expression, rewrite body to drop the curly braces, return keyword, and semicolon.
Specifically: …
=> Add linter to convert PHP anonymous functions to lambdas

CONTRIBUTING.md, src/Linters/NoEmptyStatementsLinter.php, tests/NoEmptyStatementsLinterTest.php, tests/fixtures/NoEmptyStatementsLinter/empty_statements.php.autofix.expect, tests/fixtures/NoEmptyStatementsLinter/empty_statements.php.expect, tests/fixtures/NoEmptyStatementsLinter/empty_statements.php.in
This linter addresses #110.
I'd like input on two areas in particular:
1. The language of the error. Is there something more helpful/friendly to say than "Delete this empty statement"?
2. Whitespace management
I was unsure how much whitespace management to do in this particular linter. I think there are a few options:
- Do nothing (remove the entire expression, including leading and trailing whitespace)
- Retain all whitespace (just remove the semicolon, current implementation)
- Retain only newline whitespace
I started with do nothing. My thinking was to punt and let `hackfmt` handle reformatting. But the autofix output looked pretty bad, so I tried to retain all the leading/trailing whitespace. It looks fine but can cause other errors (e.g. trailing whitespace). Retaining only newlines …
=> Add linter banning empty statements

bin/hhast-migrate
- Fix issue while trying to run hhast-migration from composer binary folder.
```
➜  waffle git:(master) ✗ ./vendor/bin/hhast-migrate 
Fatal error: Uncaught Error: require_once(/home/saif/projects/waffle/vendor/hhvm/hhast/bin/../vendor/hh_autoload.php): File not found in /home/saif/projects/waffle/vendor/hhvm/hhast/bin/hhast-migrate:14
Stack trace:
#0 {main}
➜  waffle git:(master) ✗ 
```
- use `runAsync` instead of the deprecated method `main` 
see : https://github.com/hhvm/hh-clilib/blob/master/src/CLIBase.hh#L148
=> Fix autoloading issue 

src/SchemaVersionError.php
Schema version errors currently throw a pretty cryptic exception due to `as int` being used on a float. This fixes to use intdiv, and also fixes a missing quote in the exception string.
```
Exception: TypeAssertionException
Message: Expected int, got float
Trace:
#0 /Users/ssandler/Documents/dev/webapp/vendor/splinter/vendor/hhvm/hhast/src/entrypoints.php(21): Facebook\HHAST\SchemaVersionError->__construct()
#1 /Users/ssandler/Documents/dev/webapp/vendor/splinter/vendor/hhvm/hhast/src/entrypoints.php(124): Facebook\HHAST\from_json()
```
```
Exception: Facebook\HHAST\SchemaVersionError
Message: In file "! no file !": AST version mismatch: expected '2018-07-19-0001' (3.29.0), but got '2018-10-30-0001'
Trace:
#0 /Users/ssandler/Documents/dev/webapp/vendor/splinter/vendor/hhvm/hhast/src/entryp …
```
=> fix integer division and missing quote in SchemaVersionError

src/nodes/NamespaceDeclaration.hack, tests/ResolutionTest.hack
This prevents an error with
```php
namespace Name\Space {
class A {
}
class B {
}
}
```
where the given namespace is `Name\Space\A\B`
Happy to make a test if you want.
=> Limit descendants to namespace name

src/Migrations/AssertToExpectMigration.hack, src/Migrations/ImplicitShapeSubtypesMigration.hack, src/__Private/Asio/AsyncConditionNode.hack, src/__Private/LSPImpl/ExecuteCommandCommand.hack, src/__Private/LintRunConfig.hack, src/__Private/XHProf.hack, src/__Private/codegen/CodegenSyntax.hack, src/__Private/codegen/CodegenTokens.hack, src/nodes/EditableNode.hack, tests/FixtureRewritingTest.hack, tests/MigrationsTest.hack
Summary: required for .hhconfig disable_lval_as_an_expression and disallow_ambiguous_lambda.
=> Lambda and lval

src/Linters/NoElseifLinter.hack, src/__Private/LintRunCLIEventHandler.hack, src/__Private/LintRunConfig.hack, tests/NoElseifLinterTest.hack, tests/fixtures/NoElseifLinter/elseif.php.autofix.expect, tests/fixtures/NoElseifLinter/elseif.php.expect, tests/fixtures/NoElseifLinter/elseif.php.in, tests/fixtures/NoElseifLinter/elseif_leading_trailing.php.autofix.expect, tests/fixtures/NoElseifLinter/elseif_leading_trailing.php.expect, tests/fixtures/NoElseifLinter/elseif_leading_trailing.php.in
Summary: linter for `elseif` => `else if`.
Fixes #114
=> Implement NoElseifLinter

src/Linters/NoPHPArrayLiteralsLinter.hack, tests/NoPHPArrayLiteralsLinterTest.hack, tests/examples/NoPHPArrayLiteralsLinter/arrays.php.autofix.expect, tests/examples/NoPHPArrayLiteralsLinter/arrays.php.expect, tests/examples/NoPHPArrayLiteralsLinter/arrays.php.in
Summary: try to guess when possible if it should be fixed to a vec or a
dict. Not enabled by default. Examples:
$a = array(1, 2); // should be a vec[]
$a = ['a' => 1, 'b' => 2]; // should be a dict[]
$a = []; // no fix
Fixes #81
Signed-off-by: Arthur Loiret <arthur.loiret@emerton-data.com>
=> Implement NoPHPArrayLiteralsLinter

bin/hhast-inspect, bin/hhast-lint, bin/hhast-migrate, bin/update-codegen, bin/update-codegen.hack, src/Migrations/BaseMigration.hack, src/Migrations/HSLMigration.hack, src/Migrations/TopLevelRequiresMigration.hack, src/__Private/MigrationCLI.hack, src/nodes/NodeList.hack, tests/TopLevelRequiresMigrationTest.hack, tests/examples/migrations/TopLevelRequires/all_types.php.expect, tests/examples/migrations/TopLevelRequires/all_types.php.in, tests/examples/migrations/TopLevelRequires/eight_spaces.php.expect, tests/examples/migrations/TopLevelRequires/eight_spaces.php.in, tests/examples/migrations/TopLevelRequires/empty_entrypoint.php.expect, tests/examples/migrations/TopLevelRequires/empty_entrypoint.php.in, tests/examples/migrations/TopLevelRequires/has_class_extends.hack.expect, tests/examples/migrations/TopLevelRequires/has_class_extends.hack.in, tests/examples/migrations/TopLevelRequires/has_class_implements.hack.expect, tests/examples/migrations/TopLevelRequires/has_class_implements.hack.in, tests/examples/migrations/TopLevelRequires/has_class_with_no_parents.hack.expect, tests/examples/migrations/TopLevelRequires/has_class_with_no_parents.hack.in, tests/examples/migrations/TopLevelRequires/no_entrypoint.php.expect, tests/examples/migrations/TopLevelRequires/no_entrypoint.php.in
- if there is a valid `<<__EntryPoint>>` function, move the requires there inside a lambda
- otherwise ~~, add an easily greppable `/* HH_FIXME[1002] `~~ assume it's not in strict mode and leave it alone
=> Add migration for top-level requires

src/Linters/LicenseHeaderLinter.hack, tests/examples/LicenseHeaderLinter/no_markup_header.hack.autofix.expect, tests/examples/LicenseHeaderLinter/no_markup_header.hack.expect, tests/examples/LicenseHeaderLinter/no_markup_header.hack.in
It skipped the first statement, on the assumption it was a
MarkupSection (ended by `<?hh`).
fixes #193
=> Fix LicenseHeaderLinter for .hack files

src/Linters/FinalOrAbstractClassLinter.hack, src/Linters/NoEmptyStatementsLinter.hack, src/Linters/NoStringInterpolationLinter.hack, src/Linters/UnusedVariableLinter.hack, src/Migrations/AddFixmesMigration.hack, src/Migrations/HSLMigration.hack, src/__Private/LSPLib/Server.hack, src/__Private/LintRunConfig.hack, src/__Private/LinterCLI.hack, src/__Private/codegen/CodegenSyntax.hack, src/nodes/Node.hack, src/nodes/TokenWithFixedText.hack, tests/LSPServerTest.hack, tests/RewriteBehaviorTest.hack, tests/TestLib/ExpectObj.hack, tests/UnusedVariableLinterTest.hack, tests/examples/UnusedVariableLinter/unused_foreach.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_foreach.php.expect, tests/examples/UnusedVariableLinter/unused_foreach.php.in, tests/examples/UnusedVariableLinter/unused_list.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_list.php.expect, tests/examples/UnusedVariableLinter/unused_list.php.in, tests/examples/UnusedVariableLinter/unused_subscript.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_subscript.php.expect, tests/examples/UnusedVariableLinter/unused_subscript.php.in, tests/examples/UnusedVariableLinter/unused_variable.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_variable.php.expect, tests/examples/UnusedVariableLinter/unused_variable.php.in
This change adds the `UnusedVariableLinter` which detects unused variables in a function or method body. It is based on `UnusedParameterLinter` and has the same error message and autofix suggestion.
**Approach**
The strategy used here is to classify every variable expression in a function/method body as an assignment or a use. If the variable expression being considered does not appear in the list of uses, it's an error. The details of classification are documented at `UnusedVariableLinter::classifyVariables`:
```
* An assignment is a variable expression that is one of the following:
*
* 1a. The left-hand side of a binary expression with an assignment operator
*   that is not part of the index of a subscript expression.
* 2. The key or value of a foreach clause
* 3. The members of a list …
```
=> Add linter to detect unused variables

src/Linters/UnusedVariableLinter.hack, tests/UnusedVariableLinterTest.hack
This fixes #208, where a variable inside a lambda expression that mutates an `inout` parameter of that expression is flagged as unused. This increases the potential for false negatives, an example of which is documented in the "clean" test cases.
=> Consider inout and by-ref params to lambdas always used

src/Migrations/PregWithMatchesMigration.hack, src/__Private/Resolution/get_current_uses.hack, src/__Private/Resolution/get_uses_directly_in_scope.hack, src/__Private/Resolution/resolve_name.hack, src/nodes/Script.hack, src/resolve_function.hack, tests/PregWithMatchesMigrationTest.hack, tests/ResolutionTest.hack, tests/examples/migrations/preg_with_matches.hack.expect, tests/examples/migrations/preg_with_matches.hack.in
I considered migrating to `Regex\first_match` or `Regex\every_match` where possible, but the API is quite different (returns null/nonnull vs 1/0, matches are returned instead of assigned to a variable) so the migration would end up much more complicated and still produce suboptimal code (stuff like `($matches = Regex\first_match(...)) is nonnull ? 1 : 0`, but even worse because assignments as expressions are not allowed anymore).
=> add --preg-with-matches migration

src/__Private/Resolution/get_current_namespace.hack, src/__Private/Resolution/get_current_uses.hack, src/nodes/Script.hack, tests/ResolutionTest.hack
Right now HHAST's type resolution can't handle files with multiple namespaces without body, which is, unfortunately, legal syntax.
=> handle multiple bodyless namespaces

.vscode/settings.json
This shouldn't be necessary because the Hack plugin is configured to recognize .php files that start with <?hh, but for some reason that doesn't work correctly when using remote VSCode.
Adding this override fixes it, and doesn't break anything elsewhere (even though it's redundant in most cases), so I think we can just add it here...?
=> add PHP override to .vscode/settings.json

src/Migrations/RefToInoutMigration.hack, src/Migrations/add_arguments.hack, src/Migrations/prepend_statement.hack, src/__Private/whitespace_from_nodelist.hack, src/nodes/Script.hack, tests/examples/migrations/ref_to_inout.hack.expect, tests/examples/migrations/ref_to_inout.hack.in
This implements the missing logic for migrating things like `preg_replace_callback`, where an optional by-ref parameter became a non-optional inout parameter.
e.g. from:
```php
\preg_replace_callback(
'/([a-z])/',
fun('Str\\uppercase'),
$str,
);
```
to:
```php
$__unused_inout = null;
\preg_replace_callback(
'/([a-z])/',
fun('Str\\uppercase'),
$str,
-1,
inout $__unused_inout,
);
```
Unsurprisingly, most of the code here is to deal with whitespace and comments (see examples in the test).
I've put a lot of the code into reusable functions (`add_arguments`, `prepend_statement`, `whitespace_from_nodelist`), hopefully they could be useful for future migrations too.
=> RefToInoutMigration: implement optionalToRequired

src/Migrations/RefToInoutMigration.hack, tests/examples/migrations/ref_to_inout.hack.expect, tests/examples/migrations/ref_to_inout.hack.in
Only looks at the method name, so may result in false positives -- but that's OK for now (see comments inline).
If we need to implement more complicated transformations for methods later, we may need to fix that.
=> add (limited) support for method calls

src/Linters/PocketUniversesLinter.hack, src/__Private/LintRunConfig.hack, tests/PocketAtomExpressionLinterTest.hack, tests/PocketIdentifierExpressionLinterTest.hack, tests/examples/PocketAtomExpressionLinter/atom.hack.expect, tests/examples/PocketAtomExpressionLinter/atom.hack.in, tests/examples/PocketIdentifierExpressionLinter/pu_ident.hack.expect, tests/examples/PocketIdentifierExpressionLinter/pu_ident.hack.in
Disclaimer: CI will fail on this request since it requires Hack's experimental flag to work ok. I'm working on updating that so it is no longer needed, and I'll let you know when it's the case.
Creating linter to warn users if some of their files is using
reserved syntax for Pocket Universes.
Most of the syntax should just be erased from files right now.
It might happen that : and @ are close together, which will trigger
the linter, e.g. `function foo():@soft_annotation {...}`. In such cases,
the fix is to add a space in between
**Test is not working at the moment**, failing with this error:
```
~/hhast$ ./vendor/bin/hacktest tests/PocketAtomExpressionLinterTest.hack
Fatal error: Uncaught exception 'Facebook\HackTest\InvalidTestClassException' with message 'There must be exactly one test …
```
=> [PU] Starting linter for PU syntax

src/Linters/NoByRefCallArgumentsLinter.hack, src/Linters/NoByRefParameterDeclarationsLinter.hack, src/__Private/LintRunConfig.hack, src/nodes/Node.hack, tests/NoByRefCallArgumentsLinterTest.hack, tests/NoByRefParameterDeclarationsLinterTest.hack, tests/examples/NoByRefCallArgumentsLinter/byref_arguments.hack.autofix.expect, tests/examples/NoByRefCallArgumentsLinter/byref_arguments.hack.expect, tests/examples/NoByRefCallArgumentsLinter/byref_arguments.hack.in, tests/examples/NoByRefParameterDeclarationsLinter/byref_parameters.hack.autofix.expect, tests/examples/NoByRefParameterDeclarationsLinter/byref_parameters.hack.expect, tests/examples/NoByRefParameterDeclarationsLinter/byref_parameters.hack.in
One rule for function call arguments, one for parameter declarations. AFAIK any other references are a Hack error already.
=> lint rules for &$references

src/Linters/PreferRequireOnceLinter.hack, src/__Private/LintRunConfig.hack, tests/PreferRequireOnceLinterTest.hack, tests/examples/PreferRequireOnceLinter/prefer_require_once_linter.php.autofix.expect, tests/examples/PreferRequireOnceLinter/prefer_require_once_linter.php.expect, tests/examples/PreferRequireOnceLinter/prefer_require_once_linter.php.in
This linter is not yet done, but I want it to be known that I am writing it.
This is my very first attempt at writing a linter.
It does do the detection part well.
However, it fails on the rewriting part.
It consumes this whitespace:
```
include     "string-like-expression";
^^^^       ^^^^^
```
I figured placing the whitespace between include and "string-like-expression" with a single space, should suffice.
However, this still kills all the indentation.
I hope that someone can drop a hint as a reply. :slightly_smiling_face:
=> Write require_once linter, addresses issue #160

.hhconfig, src/Linters/AutoFixingLinterTrait.hack, src/Migrations/TopLevelRequiresMigration.hack, src/__Private/Inspector/InspectorCLI.hack, src/__Private/execute_async.hack, tests/LSPServerTest.hack, tests/LinterTestTrait.hack, tests/NodeAtPositionTest.hack, tests/OffsetFromPositionTest.hack, tests/ResolutionTest.hack, tests/TestLib/TemporaryProject.hack
I want to enable this setting in my project to discourage the use of plain php arrays.
This requires that all the dependencies also meet the `disallow_array_literal` requirement.
I replaced all `array(...)` and `[...]` expressions with their `darray`/`varray` counterpart.
=> disallow_array_literal

src/__Private/is_compatible_schema_version.hack
This is the AST update.
[update AST* with reified information for PU](https://github.com/facebook/hhvm/commit/5193a75657ac268bad697510c6c7ce6e48eeeac0)
I don't know much about PU, but this seems to be a strict superset.
=> Add new compatile schema version

src/__Private/MigrationCLI.hack
fixes #245
```
% bin/hhast-migrate --migration-classname FooBar tests
'FooBar' is not a subclass of Facebook\HHAST\BaseMigration
% git diff src/ASTDeserializationError.hack
diff --git a/src/ASTDeserializationError.hack b/src/ASTDeserializationError.hack
index b670a286..9b6c9104 100644
--- a/src/ASTDeserializationError.hack
+++ b/src/ASTDeserializationError.hack
@@ -19,7 +19,7 @@ final class ASTDeserializationError extends ASTError {
\Throwable $previous,
) {
$pre = Str\slice($source, 0, $offset) |> Str\split($$, "\n");
-    $eol = Str\search($source, "\n", $offset);
+    $eol = \strpos($source, "\n", $offset);
$pre_line = C\lastx($pre);
$rest = Str\slice($source, $offset, $eol === null ? null : $eol - $offset);
$line = $pre_line.$rest;
% bin/hhast-migrate --classname …
```
=> Add `bin/hhast-migrate --migration-classname FooBar`

src/__Private/Inspector/InspectorCLI.hack, src/__Private/Inspector/inspector.css, src/__Private/Inspector/inspector.js, src/__Private/Inspector/syntax.css
hhast-inspect is borderline unusable in Chrome (though works fine in
Safari):
- it is incredibly slow to render, visibly rendering a line at a time
- hit tests take several seconds before it even touches the JS
Stop mirroring the AST in the DOM; instead, only put the tokens in the
DOM, but preserve the AST data in attributes. This gives us a flat and wide DOM tree instead of a super-deep one.
=> faster hhast-inspect (chrome fix)

codegen/inferred_relationships.hack, codegen/syntax/AnonymousFunctionUseClause.hack, codegen/syntax/DarrayTypeSpecifier.hack, codegen/syntax/MapArrayTypeSpecifier.hack, codegen/syntax/NullableAsExpression.hack, codegen/syntax/ReturnStatement.hack, codegen/syntax/TypeArguments.hack, src/__Private/codegen/data/AsComplexTypesSyntaxExample.hack, src/__Private/codegen/data/ClassnameArrayKeySyntaxExample.hack, src/__Private/codegen/data/PHPAnonymousFunctionEmptyUseSyntaxExample.hack
Permitted nesting is not actually defined anywhere; both HackAST and
HHAST infer by looking at the Hack and HHVM unit tests. In HHAST's case,
there's also support for examples of specific things we know aren't
covered.
Explicitly testing `?as vec<_>` in Hack seems unnecessary: we test
`as vec<_>`, and that `?as` is maybe - no need to duplicate all the `as`
tests for `?as`.
Workflow:
1. add `*SyntaxExample.hack` files (**must** match this glob pattern)
2. check the HHVM version id from `codegen/version.hack`
3. install that version of HHVM
4. grab the source for that version of HHVM
5. `bin/update-codegen --rebuild-relationships --hhvm-path=$PATH_TO_CHECKOUT`;
this should be executed by the version of HHVM you just installed
6. Make sure there are no changes to `codegen/version.hack`; an …
=> Add syntax examples for edge cases

src/__Private/LintRunConfig.hack
We would break BC otherwise.
Also, projects that use PascalCase shouldn't be forcefully convinced.
=> Make ShoutCaseEnumMembersLinter non-default

src/Linters/DontAwaitInALoopLinter.hack, tests/examples/DontAwaitInALoopLinter/excluded.hack.expect, tests/examples/DontAwaitInALoopLinter/excluded.hack.in
- should not complain if await-ing in the part of the for/foreach loop that doesn't actually loop
- unless that loop is itself inside another loop
- the "closest function body" boundary wasn't correctly handled in the pretty-printer
Fixes #257
=> fix DontAwaitInALoopLinter edge cases

src/__Private/LintRunConfig.hack
We have a project with ~50 hack files at the top level folder.
We want to lint them too, so we set our roots to `["."]`.
This makes it so hhast will lint all files in all folders.
We have added a override to not scan vendor.
This works in `vendor/bin/hhast-lint` already,
but the vscode intergration doesn't play nicely with this.
The paths the errors are reported on are not normalized.
Hhast reports errors at paths like
/path/to/./project/file.hack.
The problem explorer understands the non normal path.
However, the error go away when opening the file.
This commit strips the leading `./` that is added by having . in roots.
=> Allow "." to be used as a root.

codegen/syntax/DarrayIntrinsicExpression.hack, codegen/syntax/TupleExpression.hack, codegen/syntax/VarrayIntrinsicExpression.hack, codegen/syntax/VectorIntrinsicExpression.hack, src/Migrations/PHPArrayLiteralsMigration.hack, src/__Private/MigrationCLI.hack, src/__Private/codegen/CodegenBase.hack, src/nodes/NodeList.hack, tests/PHPArrayLiteralsMigrationTest.hack, tests/examples/migrations/PHPArrayLiterals/array_parens.hack.expect, tests/examples/migrations/PHPArrayLiterals/array_parens.hack.in, tests/examples/migrations/PHPArrayLiterals/square_brackets.hack.expect, tests/examples/migrations/PHPArrayLiterals/square_brackets.hack.in
Also extend IExpression and IContainer so more types are valid.
The square brackets migration is not supported on 4.44 or above, as they
can not be parsed.
fixes #259
=> Migrate PHP array literals to varray and darray

codegen/syntax/ClassishDeclaration.hack, src/Migrations/AddXHPChildrenDeclarationMethodMigration.hack, src/Migrations/XHPChildrenDeclarationMethodMigration.hack, src/__Private/MigrationCLI.hack, src/__Private/codegen/CodegenBase.hack, src/nodes/IDeclaration.hack, tests/AddXHPChildrenDeclarationMethodMigrationTest.hack, tests/examples/migrations/AddXHPChildrenDeclarationMethod/basic_behavior.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/basic_behavior.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/leading_trivia.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/leading_trivia.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/namespace_blocks.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/namespace_blocks.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/no_children.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/no_children.hack.in
I'm not handling formatting: this is complicated enough that doing so feels like it would be reimplementing hackfmt in hhast. I'm expecting (and going to document) users should use `git diff | hackfmt --diff` after this.
In addition to the unit tests:
```
fredemmott@fredemmott-mm1 xhp-lib % gh pr status
Relevant pull requests in hhvm/xhp-lib
Current branch
#217  Child validation: support `x:composable-element... [fredemmott:composable-element-children]
- Checks passing
... snip ....
fredemmott@fredemmott-mm1 xhp-lib % ~/code/hhast/bin/hhast-migrate --add-xhp-children-declaration-method src
fredemmott@fredemmott-mm1 xhp-lib % hh_client
No errors!
fredemmott@fredemmott-mm1 xhp-lib % vendor/bin/hacktest tests
...............................................................................S.SSS …
```
=> Add hhast-migrate --add-xhp-children-declaration-method

src/Migrations/XHPClassModifierMigration.hack, src/__Private/MigrationCLI.hack, tests/XHPClassModifierMigrationTest.hack, tests/examples/migrations/xhp_class_modifier.hack.expect, tests/examples/migrations/xhp_class_modifier.hack.in
`class :foo:bar` -> `xhp class foo:bar`
Also re-does the demangling as it's not a runtime change, and it is
required - really needs the separate `--demangle-xhp` migration first
though, as callsites also need to be changed.
=> Add `hhast-migrate --xhp-class-modifier`

codegen/version.hack, src/SchemaVersionError.hack, src/__Private/codegen/CodegenVersion.hack
before
AST version mismatch: expected '2020-04-06-0001' (40.53.0), but got '2020-04-14-0002
after
AST version mismatch: expected '2020-04-06-0001' (4.53.0), but got '2020-04-14-0002
=> Make the version error correct using \HHVM_VERSION

src/Linters/DataProviderTypesLinter.hack, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.autofix.expect, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.expect, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.in
This ?T test never triggers, since `?` is its own token.
The means that `?Tk` explodes into `?` and `Tk`.
This caused a false positive while migrating hacktest.
```
DataProviderTypes: Potential type error: Parameter 1 on method testFilterNulls is of type
KeyedTraversable<Tk,?Tv>, but the DataProvider provides KeyedTraversable<mixed,mixed>
```
The rule is that you can assign anything to a generic, but `?Tv` destroys that.
=> Remove dead code typehint nodes never start with `?T`

src/Linters/DataProviderTypesLinter.hack, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.autofix.expect, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.expect, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.in
https://github.com/hhvm/hsl/pull/132#discussion_r411768035
> I think the right fix here would be to add a special case to the linter so that it understands that mixed can match a nullable type (mixed is the only type that can, so this would be just that one special case).
> 
> The function is typed as generic `?T`, I don't think we want to change that to `mixed`.
>
=> Write a special exception for `mixed` assign to `?`

src/Linters/NoPHPArrayLiteralsLinter.hack, src/__Private/is_compatible_schema_version.hack, tests/NoPHPArrayLiteralsLinterTest.hack
While I'm here, clean up old schema versions
=> Add compatible schema, skip PHP array literals linter on 4.65

src/__Private/CodegenCLI.hack, src/__Private/Inspector/InspectorCLI.hack, src/__Private/LSPImpl/Client.hack, src/__Private/LSPImpl/Server.hack, src/__Private/LintRunCLIEventHandler.hack, src/__Private/LintRunJSONEventHandler.hack, src/__Private/LinterCLI.hack, src/__Private/MigrationCLI.hack, tests/LSPServerTest.hack
closes #305
fixes #305
I have ctrl+f'ed the codebase and replaced writeAsync() with writeAllAsync() if at least one criterion is met:
- This is output intended for the programmer in the CLI (messages should be completed).
- This is clearly English text (sentences should be completed).
- This is sent in a context where the byte count matters (lsp has a concept of content length, missing bytes could end up garbling the communication)
- This is JSON (incomplete JSON is not parse-able).
I was left with one use that I can't audit with my current knowledge.
https://github.com/hhvm/hhast/pull/309/files#diff-02a3273e73a8a328d589c683a48465b6R85
=> Audit uses of writeAsync()

tests/NodeTypesTest.hack
This test in itself seems good, however I'm still getting parse
errors on the new xhp-lib. Need to investigate more, but this is
likely good regardless.
=> Add unit test for new XHP class syntax

src/Migrations/HardenVarrayOrDarrayTypehintsMigration.hack, src/Migrations/PHPArrayTypehintsMigrationBase.hack, src/Migrations/PHPArrayTypehintsMigrationBestGuess.hack, src/Migrations/PHPArrayTypehintsMigrationHard.hack, src/Migrations/PHPArrayTypehintsMigrationSoft.hack, src/__Private/MigrationCLI.hack, tests/HardenVarrayOrDarrayTypehintsMigrationTest.hack, tests/PHPArrayTypehintsMigrationBestGuessTest.hack, tests/PHPArrayTypehintsMigrationHardTest.hack, tests/PHPArrayTypehintsMigrationSoftTest.hack, tests/examples/migrations/harden_varray_or_darray_typehints.hack.expect, tests/examples/migrations/harden_varray_or_darray_typehints.hack.in, tests/examples/migrations/php_array_typehints_migration_best_guess.hack.expect, tests/examples/migrations/php_array_typehints_migration_best_guess.hack.in, tests/examples/migrations/php_array_typehints_migration_hard.hack.expect, tests/examples/migrations/php_array_typehints_migration_hard.hack.in, tests/examples/migrations/php_array_typehints_migration_soft.hack.expect, tests/examples/migrations/php_array_typehints_migration_soft.hack.in
```
--php-array-typehints-soft
Migrate array typehints to <<__Soft>> varray_or_darray (safe)
--php-array-typehints-hard
Migrate array typehints to varray_or_darray (safe only in HHVM 4.68+)
--harden-varray-or-darray-typehints
Remove <<__Soft>> from varray_or_darray typehints (recommended after migrating to HHVM 4.68+)
--php-array-typehints-best-guess
Migrate array typehints to <<__Soft>> varray or <<__Soft>> darray (likely to cause runtime warnings)
```
Review only last commit, the rest is #310 
The `--php-array-*` migrations share most of the code in a common base class.
=> migrations for array typehints

.gitattributes, .github/workflows/build-and-test.yml, .hhconfig, .travis.yml, codegen/inferred_relationships.hack, codegen/syntax/PostfixUnaryExpression.hack, codegen/syntax/XHPChildrenDeclaration.hack, codegen/syntax/XHPChildrenParenthesizedList.hack, composer.json, src/Migrations/AddXHPChildrenDeclarationMethodMigration.hack, src/Migrations/RemoveXHPChildDeclarationsMigration.hack, src/__Private/MigrationCLI.hack, src/__Private/codegen/data/XHPChildrenSyntaxExample.hack, tests/AddXHPChildrenDeclarationMethodMigrationTest.hack, tests/NodeTypesTest.hack, tests/RemoveXHPChildDeclarationsMigrationTest.hack, tests/examples/migrations/AddXHPChildrenDeclarationMethod/basic_behavior.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/basic_behavior.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/leading_trivia.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/leading_trivia.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/namespace_blocks.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/namespace_blocks.hack.in, tests/examples/migrations/AddXHPChildrenDeclarationMethod/no_children.hack.expect, tests/examples/migrations/AddXHPChildrenDeclarationMethod/no_children.hack.in, tests/examples/migrations/remove_xhp_child_declarations.hack.expect, tests/examples/migrations/remove_xhp_child_declarations.hack.in
- adds back `codegen/data/XHPChildrenSyntaxExample.hack` and regenerates the codegen files (this makes it possible for HHAST to parse XHP children declarations again)
- adds back the 2 removed XHP children migrations (turns out they actually work fine in latest HHVM with the regenerated codegen, doesn't matter that the typechecker complains about any children declarations)
- adds `disable_xhp_children_declarations=false` to `.hhconfig` so that the XHP children example file doesn't cause Hack errors (they are not FIXMEable)
- adds `src/codegen/data/ export-ignore` so that any projects depending on HHAST don't need `.hhconfig` changes
- minimum HHVM version back to 4.72, since the XHP children change was the only non-trivial incompatibility from #321
=> bring back XHP children migrations, revert version bump

.hhconfig
Removed options which have been dead for some time.
Usage: https://github.com/hhvm/user-documentation/pull/923/commits/2590eb0eb84290f0690d7040622bcdfdcaf1a2c6
=> Clean up hhconfig, it is used in user-documentation

src/Linters/DontUseAsioJoinLinter.hack, src/Linters/NamespacePrivateLinter.hack, src/Migrations/XHPLibV3ToV4Migration.hack, src/__Private/LintRunConfig.hack, src/__Private/Resolution/get_current_uses.hack, src/__Private/Resolution/get_uses_directly_in_scope.hack, src/__Private/Resolution/resolve_name.hack, src/nodes/Script.hack, src/resolve_function.hack, src/resolve_type.hack, tests/ResolutionTest.hack, tests/examples/NamespacePrivateLinter/namespace_private_only_ns_banned.php.expect
- adds relevant `use` clauses to return values of resolution functions
- uses this to improve the `NamespacePrivateLinter` error message
Prior versions would blame the entire file in the error message; now:
```
Artifacts belonging to a namespace are private to the parent namespace
Linter: Facebook\HHAST\NamespacePrivateLinter
Location: /Users/fredemmott/code/hhast-inspect/src/InspectorCLI.hack:15:9
Code:
>HH\Lib\_Private\PHPWarningSuppressor
```
=> Add some blame information to namespace resolution/info

composer.json
4.89 and 4.90 was skipped, we probably want to require an existing HHVM version here?
On the other hand, there were several nightly releases tagged 4.89-dev which would also satisfy the original requirement -- maybe we want to preserve that? I'm not sure what's preferable.
Either way the release should probably be tagged as HHAST 4.91.0
=> require HHVM 4.91 ?

codegen/inferred_relationships.hack, codegen/schema.json, codegen/syntax/AnonymousFunction.hack, codegen/syntax/EnumDeclaration.hack, codegen/syntax/EnumUse.hack, codegen/syntax/FunctionDeclarationHeader.hack, codegen/syntax/LambdaSignature.hack, codegen/syntax/ParameterDeclaration.hack, codegen/token_from_data.hack, codegen/tokens/ReadonlyToken.hack, codegen/version.hack, src/Linters/PreferLambdasLinter.hack, src/Migrations/AddXHPChildrenDeclarationMethodMigration.hack, src/__Private/is_compatible_schema_version.hack, tests/AppendToNodeListTest.hack
The schema is backwards compatible, but the generated code isn't (there's a new argument in the middle for a bunch of constructors). Do we want to release that as 4.94.1 or 4.95.0?
=> update schema (2021-01-22-0001)

src/Linters/GroupUseStatementsLinter.hack, src/Linters/LinterException.hack, src/Linters/UnusedParameterLinter.hack, src/Linters/UnusedVariableLinter.hack, tests/RewriteBehaviorTest.hack, tests/examples/UnusedParameterLinter/function_param.php.autofix.expect, tests/examples/UnusedParameterLinter/function_param.php.expect, tests/examples/UnusedParameterLinter/function_param.php.in, tests/examples/UnusedVariableLinter/unused_variable.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_variable.php.expect, tests/examples/UnusedVariableLinter/unused_variable.php.in
Fixes #341
- improves some other cases (unused params/variables *inside* lambdas are caught)
- some false negatives still exist (using a shadowed param/variable inside a lambda also marks it as used in the enclosing function) -- probably fixable but I didn't want to do too much in one PR
=> add lambda support to Unused.*Linter

src/Linters/NoEmptyStatementsLinter.hack, tests/examples/NoEmptyStatementsLinter/type_error_thrown_on_autofix.php.autofix.expect, tests/examples/NoEmptyStatementsLinter/type_error_thrown_on_autofix.php.expect, tests/examples/NoEmptyStatementsLinter/type_error_thrown_on_autofix.php.in
Inspired by https://github.com/hhvm/hhast/issues/146
Fixes: _Argument 5 passed to Facebook\HHAST\IfStatement::\_\_construct() must implement interface Facebook\HHAST\IStatement, Facebook\HHAST\NodeList given._
First commit demonstrates the failure.
This also fixes #146, since we replace the `;` with `{}` when dealing with control flow body_likes.
=> Make autofix suggestion of NoEmptyStatementsLinter safe (previously caused fatal error)

src/nodes/Node.hack
Working with `\var_dump()` in hhast doesn't work most of the time.
Nodes often refer to themselves via another object.
This causes `var_dump()` to print the recursion until the recursion limit is reached.
Also add `->toDebugTree()`, which has the same contents are `__debugInfo()`,
but you can use IDE features to expand sections and walk the tree (see example).
=> Make var_dump on a node more readable

src/Linters/UnusedVariableLinter.hack, tests/UnusedVariableLinterTest.hack, tests/examples/UnusedVariableLinter/unused_variable.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_variable.php.expect, tests/examples/UnusedVariableLinter/unused_variable.php.in
Fixes #354.
The fix I came up with is just to bail out immediately if the variable expression is part of a `MemberSelectionExpression`, as these can never result in unused variables. For example:
* `$this->x = 1`. All variables are used.
* `$x = $this->y` .`$this` is used. `$x` will be linted separately.
I don't love introducing a special case for `MemberSelectionExpression`, however, and I'm wondering how else I might approach this. This is my first time hacking on HHAST so suggestions are very welcome.
Thanks!
=> Allow MemberSelectionExpressions as defaults in function headers

src/Linters/MustUseBracesForControlFlowLinter.hack, tests/examples/MustUseBracesForControlFlowLinter/all_statement_types.php.autofix.expect, tests/examples/MustUseBracesForControlFlowLinter/all_statement_types.php.expect, tests/examples/MustUseBracesForControlFlowLinter/all_statement_types.php.in
for and do were checked, but could not be fixed.
This resulted in an invariant exception.
=> Fix MustUseBracesForControlFlowLinter autofix

src/get_unresolved_referenced_names.hack, tests/UnusedUseClauseLinterTest.hack
This teaches the linter to treat `x<>` as a function usage of `x`.
`use namespace HH\Lib\C; C\count<>` is still namespace usage of `C`.
=> Bug fix UnusedUseClauseLinter unqualified function reference syntax

.devcontainer/devcontainer.json
This PR adds the configuration for a dev container, which could be used in the [Visual Studio Code Remote - Containers](https://code.visualstudio.com/docs/remote/containers) extension.
=> Add the configuration for a dev container

.hhconfig
```
hh_client
```
```
Naming[2012] Name already bound: Facebook\HackCodegen\CLIVerifier [1]
-> Previous definition is here [2]
/workspaces/hhast/vendor/facebook/hack-codegen/bin/hh-codegen-verify-signatures.hack:15:13
13 | use namespace HH\Lib\{C, Vec};
14 | 
[1] 15 | final class CLIVerifier {
16 |   private vec<string> $targets;
17 | 
/workspaces/hhast/vendor/bin/hh-codegen-verify-signatures.hack:15:13
13 | use namespace HH\Lib\{C, Vec};
14 | 
[2] 15 | final class CLIVerifier {
16 |   private vec<string> $targets;
17 | 
Naming[2012] Name already bound: Facebook\HackCodegen\verify_signatures_main [1]
-> Previous definition is here [2]
/workspaces/hhast/vendor/facebook/hack-codegen/bin/hh-codegen-verify-signatures.hack:84:10
82 | 
83 | <<__EntryPoint>>
[1] 84 | function …
```
=> Suppress the errors about name already bound

.github/workflows/build-and-test.yml, composer.json
The upcoming commits in #368 will include a test against an `hh_client` lint rule not in 4.123.
=> Upgrade HHVM version to 4.126

src/Linters/LintError.hack, src/Linters/LintRule.hack, src/Linters/Linter.hack, src/Linters/SingleRuleLintError.hack, src/Linters/SingleRuleLinter.hack
Reviewing each commit one by one would be easier, because there are multiple commits, which are too messy when reviewing them together.
=> Separate SingleRuleLinter into Linter and LintRule

src/Linters/LinterException.hack
Originally a LinterException is associated with a `BaseLinter`, which was renamed `SingleRuleLinter`. This PR instead let a `LinterException` be associated with the more general `Linter`.
This PR is not backward compatible.
(All the commits except the last commit are included in other PRs)
=> Let LinterException support Linter

src/File.hack, src/Linters/SuppressibleTrait.hack
This dict returned by `lintMarkers` can be reused by all the linters, reducing repeated string search.
=> Add the `File::errorCodesToSuppress` method, which scans a source file for all lint markers

src/Linters/HHClientLinter.hack, tests/examples/HHClientLinter/invalid_null_check.hack.expect
See `invalid_null_check.hack.expect`. The dollar sign should be included.
=> Treat 'start' and 'end' returned by `hh_client --lint` as a 1-based inclusive range

bin/hhast-dump, bin/hhast-dump.hack, src/__Private/DumpCLI.hack
This is primarily for debugging HHAST itself, for cross-checking with
`hh_parse --full-fidelity-json` - for example, to distinguish between missing and 0-width nodes.
hh_parse remains the recommended way to canonically verify the parser's
behavior.
hhast-inspect (https://github.com/hhvm/hhast-inspect) remains the
recommended way to explore the AST of large files.
This distinction is useful when inspecting
=> Add simplified hhast-dump utility

.vscode/extensions.json
Not sure if we should recommend git extensions, but we definitely want to recommend the Hack extension.
Unlike the extensions installed from `.devcontainer/devcontainer.json`, the extensions in `extensions.json` works for workspaces that are not in a container or Codespace. See [this document](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) for more information.
=> Add VS Code extensions to recommendations

src/Linters/HHClientLinter.hack, tests/HHClientLinterIgnoreExceptTest.hack, tests/HHClientLinterIgnoreTest.hack
`keyset` is not supported according to this comment https://github.com/hhvm/hhast/commit/d12431fae2b37c60adff94fce7407e9ea933007f#diff-ab40415ae577f35a66424f1507ecc7dc1dd41322b54f8a5095ccf1d3f8ceb3c6R72-R73
=> Use `vec` instead of `keyset` in `HHClientLinter::TConfig`

src/Linters/HHClientLinter.hack, src/__Private/ProcessExecutionQueue.hack, src/__Private/ProcessExecutionQueues.hack, src/entrypoints.hack
`ParserQueue` is generalized and reused in this PR
=> Limit the maximum number of hh_client processes to run in parallel

src/Linters/HHClientLinter.hack
This PR allows for unknown fields in the configuration of `HHClientLinter` so that:
- we can use the additional fields as comments
- we can keep the forward compatibility when adding new fields
#Thanks @lexidor for discovering the issue in https://github.com/hhvm/hhast/pull/402#issuecomment-978066789
=> Allow for unknown fields in the configuration of HHClientLinter

src/__Private/LintRunConfig.hack
Having it here enables it with the `all` option, but #408 and #409 are release blockers
It should be possible to enable this just for HHAST via `extraLinters` in the config, in a followup, but on vacation atm so doing the minimum here to get `main` back to a releasable state
=> Remove HHClientLinter from NON_DEFAULT_LINTERS

hhast-lint.json, src/__Private/LintRunConfig.hack
Even though we don't want to include HHClientLinter in the `NON_DEFAULT_LINTERS` for now, it is still beneficial to dogfood the linter in the hhast repository. This PR is based on #411 and additionally add Facebook\HHAST\HHClientLinter to extraLinters
=> Add Facebook\HHAST\HHClientLinter to extraLinters

src/__Private/LintRun.hack, src/__Private/LintRunConfig.hack, src/__Private/LinterCLI.hack, test-data/hhast-lint.json, tests/IgnorePHPFilesTest.hack, tests/LinterConfigTest.hack
I added a `cwd` parameter to `LinterCLI` for the test purpose so we could test it without actual `chdir`, in case of interfering other tests.
=> Mismatched configuration for a linter should fail the lint run (fix #405)

hhast-lint.json, src/Migrations/AddXHPChildrenDeclarationMethodMigration.hack
This PR is to fix a 5607 linter error under `src/Migrations`. I reviewed `$t->getLeading() !== $t->getLeadingWhitespace()` and I believe the condition is always `true`, therefore, I removed the `if` clause.
=> Don't ignore 5607 lint error under src/Migrations and fix an existing 5607 lint error

src/Linters/HHClientLinter.hack
=> By default ignore 5639 error code from hh_client --lint

src/Linters/HHClientLinter.hack, tests/HHClientDuplicatedLintErrorTest.hack, tests/HHClientLinterIgnoreExceptTest.hack, tests/HHClientLinterIgnoreTest.hack, tests/HHClientLinterTest.hack, tests/HHClientLinterTestTrait.hack, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.autofix.expect, tests/examples/DataProviderTypesLinter/aa_test_typechecks.hack.in, tests/examples/NamespacePrivateLinter/namespace_private_type_annotation.php.in, tests/examples/NoEmptyStatementsLinter/type_error_thrown_on_autofix.php.autofix.expect, tests/examples/NoEmptyStatementsLinter/type_error_thrown_on_autofix.php.in, tests/examples/UnusedVariableLinter/unused_foreach.php.autofix.expect, tests/examples/UnusedVariableLinter/unused_foreach.php.in
`HHClientDuplicatedLintErrorTest` ensures that no lint error is found by `HHClientLinter` in examples for `SingleRuleLinter`s, closing #409.
=> Add a test to detect duplicated lint rules

src/__Private/is_compatible_schema_version.hack
#435 supported AST version 2022-01-18-0001 but did not support AST version 2021-12-08-0001, which is the AST version produced by HHVM 4.145.0. This PR supported both 2022-01-18-0001 and 2021-12-08-0001.
- HHVM 4.144.0 produces the AST version `2021-09-13-0001`.
- HHVM 4.145.0 and nightly-2022.01.19 share the same code base and produce the AST version `2021-12-08-0001`, according to https://github.com/facebook/hhvm/commit/4c03fbf28cb0bfb1fbda537d1e5ed3ad2da22cfd
- HHVM nightly-2022.01.20+  produces the AST version `2022-01-18-0001`, according to https://github.com/facebook/hhvm/commit/f14308e07cc39df307d6576f57fcf80db611a9f8
=> Support AST version 2021-12-08-0001

src/__Private/LintRunCLIEventHandler.hack
The original implementation is not type safe and there was an existing `HH_FIXME[4110]` marker to suppress the error. Unfortunately the marker is not adequate in the nightly HHVM because of the newly introduced 4323 error.
This PR suppresses the error 4323 and should fix the CI.
=> Suppress the 4323 typing error

src/Linters/UnreachableCodeLinter.hack, tests/UnreachableCodeLinterTest.hack, tests/examples/UnreachableCodeLinter/unreachable.php.expect, tests/examples/UnreachableCodeLinter/unreachable.php.in
This PR adds UnreachableCodeLinter which flags any `return`, `throw`, or `continue` statement that is followed by other code at the same scope (CompoundStatement is used to approximate "same scope").
This is probably best implemented in the typechecker which can do better analysis than a linter, but as an intermediate solution this might help folks identify potential bugs.
=> Add linter to identify unreachable code

src/__Private/XHProf.hack
This makes it typecheck with nightly hh_client.
=> Add explicit type to lambda argument.

src/Linters/UnusedPipeVariableLinter.hack, tests/UnusedPipeVariableLinterTest.hack, tests/examples/UnusedPipeVariableLinter/unused_pipe.php.expect, tests/examples/UnusedPipeVariableLinter/unused_pipe.php.in
This PR introduces `UnusedPipeVariableLinter` to identify bugs where the pipe variable `$$` is missing from a pipe operation.
I recently encountered a bug in a pipe operation where the right-hand side re-used the initial variable, discarding the intended input in `$$`:
```hack
$output = htmlspecialchars($html) |> format($html);
```
Note that the docs for ["Expressions And Operators: Pipe"](https://docs.hhvm.com/hack/expressions-and-operators/pipe) say:
> The binary pipe operator, `|>`, evaluates the result of a left-hand expression and stores the result in `$$`, the pre-defined pipe variable. The right-hand expression _must_ contain at least one occurrence of `$$`.
If it's a bug that the typechecker does not produce an error for a missing `$$`, we can close this PR and file an issue in …
=> Add UnusedPipeVariableLinter

.gitattributes, .github/workflows/build-and-test.yml, codegen-no-rebuild/latest_breaking_version.hack, codegen/inferred_relationships.hack, codegen/node_from_json.hack, codegen/schema.json, codegen/syntax/CtxInRefinement.hack, codegen/syntax/EnumClassDeclaration.hack, codegen/syntax/LambdaExpression.hack, codegen/syntax/SimpleTypeSpecifier.hack, codegen/syntax/TraitUse.hack, codegen/syntax/TypeInRefinement.hack, codegen/syntax/TypeRefinement.hack, codegen/syntax/VectorTypeSpecifier.hack, codegen/token_from_data.hack, codegen/tokens/WithToken.hack, codegen/version.hack, hh_autoload.json, hhast-lint.json, src/__Private/CodegenCLI.hack, src/__Private/codegen/CodegenLastestBreakingVersion.hack, src/__Private/is_compatible_schema_version.hack
- The job `update-schema` is added to Github Actions.
- It is executed everyday to create pull requests to update schema if it the schema changes. One for breaking change and one for backward compatible change. The maintainer can review the PRs to merge one of them. For example: https://github.com/Atry/hhast/pull/3 and https://github.com/Atry/hhast/pull/4
- It is also executed on pull request and will add suggestions to the pull request if it detect the schema needs regeneration.
- `src/__Private/codegen/CodegenLastestBreakingVersion.hack` is a code generator to generate `codegen-no-rebuild/latest_breaking_version.hack`, which includes the version number of latest breaking change on AST.
- `src/__Private/is_compatible_schema_version.hack` is updated to use …
=> Add Github Actions to update schema

.github/workflows/build-and-test.yml
The purpose of `update-schema` is to create pull requests, which does not make sense for a tag.
=> Skip update-schema job when it is triggered by a tag

.github/workflows/build-and-test.yml
#462 added a github action job to create pull requests. One of the pull request created by the job is to update the latest breaking version. However the pull request is unnecessary if the latest breaking version is the current version. This PR will prevent the pull request from being created when it is unnecessary.
Note that the other PR to update schema will still be created. For example, #463 and #464 are identical, so #464 is unnecessary while #463 is good.
=> Don't create the PR to update the latest breaking version if the latest breaking version is not changed

.github/workflows/build-and-test.yml
Previously, Github Action created #462, which did not update composer.json. As a result, the release tag that includes #462  breaks dependent of HHAST according to https://github.com/hhvm/definition-finder/runs/6760337843?check_suite_focus=true
This PR let the Github Action update composer.json when changing latest breaking HHVM version, in case of dependent breakage in the future.
=> Let Github Action update composer.json when changing latest breaking HHVM version

.github/workflows/build-and-test.yml
Currently, a pull request to update schema to a backward incompatible version would be created even when the schema is unchanged, such as #474, which is not useful.
This PR skips creating such a useless pull request.
=> Skip creating the pull request to update latest breaking version if the schema is unchanged

hhast-lint.json, src/Linters/DontDiscardNewExpressionsLinter.hack, src/__Private/LintRunConfig.hack, tests/DontDiscardNewExpressionsLinterTest.hack, tests/examples/DontDiscardNewExpressionsLinter/dynamic_constructors.hack.expect, tests/examples/DontDiscardNewExpressionsLinter/dynamic_constructors.hack.in, tests/examples/DontDiscardNewExpressionsLinter/forget_to_throw.hack.expect, tests/examples/DontDiscardNewExpressionsLinter/forget_to_throw.hack.in, tests/examples/DontDiscardNewExpressionsLinter/side_effect_constructor.hack.expect, tests/examples/DontDiscardNewExpressionsLinter/side_effect_constructor.hack.in
=> Add DontDiscardNewExpressionsLinter

src/Linters/HHClientLintError.hack, src/Linters/HHClientLinter.hack
This PR should fix #500 by considering new fields from `hh_client --json --lint` output as backward compatible. If new JSON fields were added to the JSON response in the future, it would not break HHAST like what we see in https://github.com/hhvm/hhast/runs/7729252032?check_suite_focus=true .
=> Consider new fields from `hh_client --json --lint` output as backward compatible

src/Linters/UnusedLambdaParameterLinter.hack, src/Linters/UnusedParameterLinter.hack, src/__Private/LSPLib/Server.hack, src/__Private/LintRunConfig.hack, src/__Private/SharedCodeForUnusedParameterLinters.hack, tests/UnusedLambdaParameterLinterTest.hack, tests/UnusedParameterLinterTest.hack, tests/examples/UnusedLambdaParameterLinter/function_param.php.autofix.expect, tests/examples/UnusedLambdaParameterLinter/function_param.php.expect, tests/examples/UnusedLambdaParameterLinter/function_param.php.in, tests/examples/UnusedLambdaParameterLinter/old_style_variadic_parameter_no_crash.php.autofix.expect, tests/examples/UnusedLambdaParameterLinter/old_style_variadic_parameter_no_crash.php.expect, tests/examples/UnusedLambdaParameterLinter/old_style_variadic_parameter_no_crash.php.in, tests/examples/UnusedLambdaParameterLinter/unused_variadic_param.php.autofix.expect, tests/examples/UnusedLambdaParameterLinter/unused_variadic_param.php.expect, tests/examples/UnusedLambdaParameterLinter/unused_variadic_param.php.in, tests/examples/UnusedParameterLinter/function_param.php.autofix.expect, tests/examples/UnusedParameterLinter/function_param.php.expect, tests/examples/UnusedParameterLinter/function_param.php.in, tests/examples/UnusedParameterLinter/old_style_variadic_parameter_no_crash.php.autofix.expect, tests/examples/UnusedParameterLinter/old_style_variadic_parameter_no_crash.php.expect, tests/examples/UnusedParameterLinter/old_style_variadic_parameter_no_crash.php.in, tests/examples/UnusedParameterLinter/unused_variadic_param.php.autofix.expect, tests/examples/UnusedParameterLinter/unused_variadic_param.php.expect, tests/examples/UnusedParameterLinter/unused_variadic_param.php.in
- Variadic parameters were not checked
function _(int ... $x): void {} now emits an error for $x.
- Lambda parameters are now linted in unparenthesized params.
$x ==> 0 now emits an error for $x.
Same applies for (int ... $x) ==> 0.
- Added explicit tests for old style variadics.
The linter handled them fine, but there was no test for it.
Checking for unparenthesized lambda parameters required a new linter.
The UnusedParameterLinter checked against ParameterDeclaration.
$x ==> 0; does not introduce one, so a new TNode was required.
This PR may cause old HHAST_FIXME comments to break.
You will have to upgrade:
/\*HHAST_FIXME[UnusedParameter]\*/ ($x) ==> 0; to
/\*HHAST_FIXME[UnusedLambdaParameter]\*/ ($x) ==> 0;
I suspect this linter is rarely suppressed, since the autofix is easier.
=> Fix some shortcomings of UnusedParameterLinter

docs/configuring-hhast-lint.md, docs/linters-usage.md, src/__Private/LintRunConfig.hack
linters-usage.md does not document these options and suggests reading the sources instead. Although the type is somewhat well commented,
I felt like a bit of conventional documentation would go a long way.
=> Document the hhast-lint.json file in detail

codegen/inferred_relationships.hack, codegen/node_from_json.hack, codegen/schema.json, codegen/syntax/AliasDeclaration.hack, codegen/syntax/AttributizedSpecifier.hack, codegen/syntax/ClassishDeclaration.hack, codegen/syntax/ClassnameTypeSpecifier.hack, codegen/syntax/ClosureTypeSpecifier.hack, codegen/syntax/EnumClassDeclaration.hack, codegen/syntax/EnumDeclaration.hack, codegen/syntax/FunctionDeclarationHeader.hack, codegen/syntax/ModuleDeclaration.hack, codegen/syntax/PackageDeclaration.hack, codegen/syntax/PackageIncludes.hack, codegen/syntax/PackageUses.hack, codegen/syntax/ParameterDeclaration.hack, codegen/syntax/PropertyDeclaration.hack, codegen/syntax/TypeArguments.hack, codegen/syntax/TypeConstraint.hack, codegen/syntax/TypeInRefinement.hack, codegen/syntax/TypeRefinement.hack, codegen/syntax/WhereConstraint.hack, codegen/token_from_data.hack, codegen/tokens/PackageToken.hack, codegen/version.hack, src/__Private/codegen/CodegenBase.hack, src/nodes/IHasTypeHint.hack
This PR let `TypeRefinement` implement `ITypeSpecifier` and the update schame version to `2022-09-29-0000`, fixing the CI on `main` branch. Without this PR, many places that were `ITypeSpecifier` now become `Node`, resulting compilation errors.
=> Let TypeRefinement implement ITypeSpecifier

src/Linters/ASTLinter.hack
There is currently an assumption in HHAST that the lint node and the error node will be the same thing, but discussions with @fredemmott indicate that assumption is unneeded. This change will check for suppressions on the error node in addition to the lint node so that we can have this work in an expected way. This should ease situations where people are trying to automatically apply suppressions from the lint errors for linters where the error node and lint node are not the same.
=> Enable lint suppressions on the error node in addition to the linted node

src/Linters/ASTLinter.hack, src/Linters/suppress_ast_linter_error.hack
This adds some functionality that allows us to get the errors with the suppressions. This will be useful when combined with getting all of the suppressions in a file to allow the removal of those suppressions that are not actively being used.
=> Create functions to get suppressions with the errors

src/get_unresolved_referenced_names.hack
Discovered this issue running on our codebase. The reference finding wasn't properly accounting for this type of node so adding it here to fix the issue we were having.
=> Fix UnusedUseClauseLinter to handle EnumClassLabelExpression nodes

src/__Private/LintRunConfig.hack, test-data/hhast-lint.json, tests/LinterConfigTest.hack
This is a regression from
https://github.com/hhvm/hhast/commit/e6b406db4f4dbe0b7f6c53832d81e1e799faae87 that removes support for multiple overrides for a single file.
This restores the support for multiple overrides for the run config, but the `linterConfigs` section is still based on the override found.
I manually tested this PR to make sure we don't regress existing tests (and new tests are still passing).
=> Fix config with multiple overrides for a single file

codegen/inferred_relationships.hack, codegen/syntax/LambdaExpression.hack, codegen/syntax/QualifiedName.hack, codegen/tokens/NameToken.hack, src/Linters/NoEmptyStatementsLinter.hack, src/Linters/UnusedUseClauseLinter.hack, src/Linters/UseStatementWIthoutKindLinter.hack, src/Migrations/HSLMigration.hack, src/__Private/codegen/CodegenBase.hack, src/__Private/codegen/CodegenRelations.hack, src/__Private/codegen/data/LambdaBody.SyntaxExample.hack, src/nodes/NodeList.hack, tests/NoParamsIsAMissingNodeTest.hack, tests/NodeListGetChildrenOfItemsOfTypeTest.hack, tests/examples/NoEmptyStatementsLinter/comparison_empty_statements.php.autofix.expect, tests/examples/NoEmptyStatementsLinter/comparison_empty_statements.php.expect, tests/examples/NoEmptyStatementsLinter/comparison_empty_statements.php.in
Fixes:
- `NoEmptyStatementsLinter`
- False negative `3 <= 4` was not treated as an empty expression.
- False negative `3 >= 4` was not treated as an empty expression.
- Comment: Mentioned `ExpressionStament::getOperator()`, should have been `BinaryOperation`.
- `NodeList::getChildrenOfItemsOfType<T>(classname<T> $classname): vec<T>`
- `T` was not inferred to be the type of the classname argument.
- Added `getChildrenOfItemsByType<reify T>()` to match `getChildrenByType<reify T>()`.
- Comment mentioned `NodeList::createEmptyListOrNull()`, which doesn't exist anymore.
- Constants may now appear as the sole expression of a lambda body.
- Codegen no longer consumes more threads than hardware threads of the machine.
And a quick formatting of the affect files.
=> Random bug fixes
