hhvm/hhast

- bin/hhast-inspect
- composer.json
- src/__Private/Inspector/InspectorCLI.php
- src/__Private/Inspector/inspector.css
- src/__Private/Inspector/inspector.js
- src/__Private/Inspector/syntax.css
Makes it easy to understand the structure of a Hack file
refs #40
Example usage:
```
$ bin/hhast-inspect src/__Private/Inspector/InspectorCLI.php
/var/folders/3l/2yk1tgkn7xdd76bs547d9j90fcbt87/T//hhast-0717bee70f59cc11c924c8e9c33ed403.html
```
> Add developer tool: hhast-inspect

- codegen/editable_node_from_json.php
- codegen/editable_token_from_data.php
- codegen/inferred_relationships.php
- codegen/schema.json
- codegen/syntax/AnonymousFunction.php
- codegen/syntax/AwaitableCreationExpression.php
- codegen/syntax/BinaryExpression.php
- codegen/syntax/CatchClause.php
- codegen/syntax/Enumerator.php
- codegen/syntax/ErrorSyntax.php
- codegen/syntax/ExpressionStatement.php
- codegen/syntax/ForeachStatement.php
- codegen/syntax/FunctionCallWithTypeArgumentsExpression.php
- codegen/syntax/IsExpression.php
- codegen/syntax/LambdaExpression.php
- codegen/syntax/ListItem.php
- codegen/syntax/MemberSelectionExpression.php
- codegen/syntax/SimpleInitializer.php
- codegen/syntax/TypeParameters.php
This includes #53 - only the last commit is specific to this PR.
> Regenerate against 3.27

- composer.lock
- src/__Private/LinterCLI.php
- src/__Private/LinterCLIErrorHandlerJSON.php
- src/__Private/LinterCLIErrorHandlerPlain.php
- src/__Private/LinterCLIMode.php
- tests/JSONOutputTest.php
Prep work for adding LSP support.
@PranayAgarwal  : I'd add you as a reviewer if I could :)
> Remove --json, add --mode. Pass in terminals to error handlers

- src/Linters/DontAwaitInALoopLinter.php
- src/Migrations/HSLMigration.php
- src/__Private/SubprocessException.php
- src/__Private/codegen/CodegenSyntax.php
- src/nodes/EditableNode.php
- src/nodes/EditableToken.php
- src/nodes/EditableTrivia.php
- src/resolve_type.php
I ran the migration on this repo and ensured the tests still pass.
> Ssandler hsl migration

- src/Migrations/AssertToExpectMigration.php
> Do not insert use function under certain conditions

- src/__Private/ParserConcurrencyLease.php
- src/__Private/codegen/CodegenRelations.php
- use the new async entrypoints to the parser
- smaller wait
- higher limit: still not particularly intensive, but actually useful
now we have a smaller wait
This gets the time from > 20 minutes to ~ 5 minutes on a mac pro
> Faster relationship regeneration

- src/__Private/LintRunLSPPublishDiagnosticsEventHandler.hack
It's rare, but we actually can finish linting one file while another
is still processing. This made the LSP server crash, which meant the
we'd need to restart jitting before anything else
> Fix race in LintRunLSPPublishDiagnosticsEventHandler

- tests/examples/GroupUseStatementAlphabetizationLinter/comma.php.autofix.expect
- tests/examples/GroupUseStatementAlphabetizationLinter/comma.php.expect
- tests/examples/GroupUseStatementAlphabetizationLinter/comma.php.in
- tests/examples/GroupUseStatementsLinter/sort.php.autofix.expect
- tests/examples/GroupUseStatementsLinter/sort.php.expect
- tests/examples/GroupUseStatementsLinter/sort.php.in
Coverage for issues fixed by Fred in 89ebe9ccab30e4b0ea446244a83524688375ceba
> Add more tests for group use linters

- src/Linters/MustUseOverrideAttributeLinter.hack
- src/ResolvedTypeKind.hack
- src/__Private/Resolution/get_current_generics.hack
- src/nodes/Script.hack
- src/resolve_type.hack
- tests/ResolutionTest.hack
This changes the public API -- if we care about that, I can instead add this as a new function.
> handle generics in resolve_type()

- codegen/syntax/AnonymousClass.hack
- codegen/syntax/Attribute.hack
- codegen/syntax/AttributeSpecification.hack
- codegen/syntax/DefineExpression.hack
- codegen/syntax/EmbeddedBracedExpression.hack
- codegen/syntax/EmbeddedMemberSelectionExpression.hack
- codegen/syntax/EmbeddedSubscriptExpression.hack
- codegen/syntax/ErrorSyntax.hack
- codegen/syntax/LiteralExpression.hack
- codegen/syntax/PUAccess.hack
- codegen/syntax/PipeVariableExpression.hack
- codegen/syntax/PocketAtomExpression.hack
- codegen/syntax/PocketAtomMappingDeclaration.hack
- codegen/syntax/PocketEnumDeclaration.hack
- codegen/syntax/PocketFieldTypeDeclaration.hack
- codegen/syntax/PocketFieldTypeExprDeclaration.hack
- codegen/syntax/PocketIdentifierExpression.hack
- codegen/syntax/PocketMappingIdDeclaration.hack
- codegen/syntax/PocketMappingTypeDeclaration.hack
- codegen/syntax/PrefixedStringExpression.hack
- codegen/syntax/TupleTypeExplicitSpecifier.hack
- codegen/syntax/VariableExpression.hack
- codegen/syntax/XHPCategoryDeclaration.hack
- codegen/version.hack
- src/__Private/codegen/CodegenSyntax.hack
The thing to review here is whether any of the affected node types are worrisome.
> use nullable ?Node for fields with unknown types

- docs/linters-development.md
Figuring this out took me 15 minutes. This will save someone some time.
> Tell people how to run their linter

- src/__Private/from_decoded_json.hack
- src/__Private/is_compatible_schema_version.hack
+added compatibility between 2019-10-03-0001 and 2019-08-22-0001
Please sanity check that I didn't put in any of the compatibility rules backwards :)
> refactor COMPATIBLE_SCHEMA_VERSIONS

- .hhconfig
- src/__Private/LSPImpl/Server.hack
- tests/LSPServerTest.hack
(Requires an update to type-assert and hhvm-autoload)
> error_php_lambdas

- src/Linters/PreferLambdasLinter.hack
- src/nodes/IExpression.hack
- tests/examples/PreferLambdasLinter/prefer_lambdas.php.autofix.expect
Resolves #252 
```
vendor/bin/hacktest tests/PreferLambdasLinterTest.hack 
....
Summary: 4 test(s), 4 passed, 0 failed, 0 skipped, 0 error(s).
```
> Optimized PreferLambdasLinter for single-line expression.

- src/Migrations/RemoveXHPChildDeclarationsMigration.hack
- src/__Private/MigrationCLI.hack
- tests/RemoveXHPChildDeclarationsMigrationTest.hack
- tests/examples/migrations/remove_xhp_child_declarations.hack.expect
- tests/examples/migrations/remove_xhp_child_declarations.hack.in
used to create hhvm/xhp-lib#224
Depends on and includes #268 - review last commit only
> Add hhast-migrate --remove-xhp-child-declarations

- src/Linters/DontUseAsioJoinLinter.hack
- src/Migrations/HSLMigration.hack
- src/Migrations/TopLevelRequiresMigration.hack
- src/__Private/LintRunConfig.hack
- src/__Private/MigrationCLI.hack
- src/__Private/codegen/CodegenRelations.hack
- src/qualified_name_is_fully_qualified.hack
- src/resolve_function.hack
- tests/AutoFixingLinterTestTrait.hack
- tests/DontUseAsioJoinLinterTest.hack
- tests/LSPServerTest.hack
- tests/LinterTestTrait.hack
- tests/examples/DontUseAsioJoinLinter/in-a-namespaced-file.hack.expect
- tests/examples/DontUseAsioJoinLinter/in-a-namespaced-file.hack.in
- tests/examples/DontUseAsioJoinLinter/not-in-a-namespaced-file.hack.expect
- tests/examples/DontUseAsioJoinLinter/not-in-a-namespaced-file.hack.in
> Implement DontUseAsioJoinLinter

- codegen/inferred_relationships.hack
- codegen/node_from_json.hack
- codegen/schema.json
- codegen/syntax/EnumAtomExpression.hack
- codegen/syntax/VectorTypeSpecifier.hack
- codegen/token_from_data.hack
- codegen/tokens/HashToken.hack
- codegen/version.hack
- src/__Private/is_compatible_schema_version.hack
Should be backwards compatible
> Update schema for 4.82

- src/Linters/MustUseBracesForControlFlowLinter.hack
- src/Linters/NoNewlineAtStartOfControlFlowBlockLinter.hack
- src/Migrations/HSLMigration.hack
- src/__Private/LintRunConfig.hack
- src/control_flow_statement_get_body_like.hack
- tests/NoNewlineAtStartOfControlFlowBlockLinterTest.hack
- tests/examples/NoNewlineAtStartOfControlFlowBlockLinter/example.php.autofix.expect
- tests/examples/NoNewlineAtStartOfControlFlowBlockLinter/example.php.expect
- tests/examples/NoNewlineAtStartOfControlFlowBlockLinter/example.php.in
> No newline at start of control flow block

- hhast-lint.json
- src/__Private/LintRunConfig.hack
- src/__Private/ProcessExecutionQueues.hack
All the existing errors are ignored for now
> Dogfood HHClientLinter for hhast source code

- src/__Private/LintRun.hack
- src/__Private/LintRunConfig.hack
The file specific linter config is used in #417
> Support file specific linter config

- .github/workflows/build-and-test.yml
- .hhconfig
- codegen/inferred_relationships.hack
- codegen/schema.json
- codegen/syntax/AsExpression.hack
- codegen/syntax/BinaryExpression.hack
- codegen/syntax/CaseLabel.hack
- codegen/syntax/ClosureTypeSpecifier.hack
- codegen/syntax/EnumClassDeclaration.hack
- codegen/syntax/EnumClassEnumerator.hack
- codegen/syntax/FunctionCallExpression.hack
- codegen/syntax/LambdaSignature.hack
- codegen/syntax/NamespaceBody.hack
- codegen/syntax/PrefixUnaryExpression.hack
- codegen/syntax/TypeConstant.hack
- codegen/token_from_data.hack
- codegen/tokens/InternalToken.hack
- codegen/version.hack
- composer.json
- src/Migrations/AddXHPChildrenDeclarationMethodMigration.hack
- src/__Private/codegen/CodegenRelations.hack
- src/__Private/codegen/data/NativeFunctions.SyntaxExample.hack
- src/__Private/is_compatible_schema_version.hack
- will fail on nightly builds as there's another schema change which is also incompatible
- probably best to review commits separately and merge without squashing
> Support HHVM 4.156

- docs/updating-schema.md
I tested shallow clone is good enough to generate the schema
> Use a shallow clone

- .github/workflows/build-and-test.yml
https://github.com/Atry/hhast/pull/9 is an example of pull request with updated description
> Improve pull request description

- .github/workflows/build-and-test.yml
> Set the author of PRs created by GitHub Actions to Hack OSS Team
